services:
  postgres:
    image: postgres:17.4
    container_name: musiccollection-postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - musiccollection

  postgres-keycloak:
    image: postgres:17.4
    container_name: musiccollection-postgres-keycloak
    env_file:
      - postgres-keycloak.env
    ports:
      - 5433:5432
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - musiccollection

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: musiccollection-keycloak
    env_file:
      - keycloak.env
    ports:
      - 8080:8080
    command:
      - start-dev
    networks:
      - musiccollection
    depends_on:
      - postgres-keycloak

  minio:
    image: minio/minio
    container_name: musiccollection-minio
    env_file:
      - minio.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - musiccollection

  app:
    image: ghcr.io/alexanderboldt/musiccollection:7.0.0
    container_name: musiccollection-app
    env_file:
      - postgres.env
      - minio.env
      - musiccollection.env
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - keycloak
      - minio
    networks:
      - musiccollection

volumes:
  postgres_data:
  postgres_keycloak_data:
  minio_data:

networks:
  musiccollection:
    name: musiccollection
    driver: bridge
