quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    migrate-at-start: true
  oidc:
    auth-server-url: http://keycloak:8080/realms/musiccollection
    application-type: service
    token:
      issuer: http://localhost:8080/realms/musiccollection
      principal-claim: sub
  s3:
    endpoint-override: http://minio:9000
    path-style-access: true
    aws:
      region: us-east-1
      credentials:
        type: static
        static-provider:
          access-key-id: ${MINIO_ROOT_USER}
          secret-access-key: ${MINIO_ROOT_PASSWORD}
