quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/musiccollection
    username: admin
    password: admin
  flyway:
    enabled: true
    migrate-at-start: true
  oidc:
    auth-server-url: http://localhost:8080/realms/musiccollection
    application-type: service
    token:
      principal-claim: sub
  s3:
    endpoint-override: http://localhost:9000
    path-style-access: true
    aws:
      region: eu-central-1
      credentials:
        type: static
        static-provider:
          access-key-id: admin
          secret-access-key: adminadmin

bucket:
  artist: artist
  album: album
