namespace: musiccollection

resources:
  - namespace.yml
  - postgres/statefulset.yml
  - postgres-keycloak/statefulset.yml
  - keycloak/deployment.yml
  - minio/statefulset.yml
  - musiccollection/deployment.yml

secretGenerator:
  - name: musiccollection-postgres-secret
    envs:
      - secrets/postgres.env
  - name: musiccollection-postgres-keycloak-secret
    envs:
      - secrets/postgres-keycloak.env
  - name: musiccollection-keycloak-secret
    envs:
      - secrets/keycloak.env
  - name: musiccollection-minio-secret
    envs:
      - secrets/minio.env
  - name: musiccollection-app-secret
    envs:
      - secrets/musiccollection.env
